[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["."]
include = ["bibforgery*"]
exclude = ["venv*", ".venv*", "build*", "dist*"]

[tool.setuptools.package-data]
"bibforgery" = [
    "templates/**/*",
    "assets/**/*"
]


[project.scripts]
bibforgery = "bibforgery.cli:main"


[project]
name = "bibforgery"
version = "1.10.22"
description = "Cliente para obtener y procesar datos de Scopus"
authors = [
    { name="Eduardo Escalante" }
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "beautifulsoup4==4.14.3",
    "bibtexparser==2.0.0b9",
    "colorama==0.4.6",
    "Jinja2==3.1.6",
    "lxml==6.1.0",
    "platformdirs==4.10.0",
    "python-dotenv==1.2.2",
    "python_docx==1.2.0",
    "Requests==2.34.2",
    "weasyprint==69.0",
]